### ISSUE TITLE
Is this compatible with MCT-340 e?

### ISSUE THREAD

**Issue by Steven-Pierce** [pakmanwg/smartthings-visonic-sensor#1]
I’ve added this device handler and can change device types to smoke, water, or contact but the state doesn’t report a change when the state changes.

**Comment by pakmanwg** [comment]
Steven, please update to the newer version 01.02. The problem should be fixed.

**Comment by Steven-Pierce** [comment]
Thanks I’ll try it tonight.

**Comment by pakmanwg** [comment]
Let me know. Thanks.

**Comment by Steven-Pierce** [comment]
What would I change to make Closed = clear and open = detected for smoke?

________________________________

**Comment by pakmanwg** [comment]
Make sure in your IDE, select the new device handler for your visonic device.
Then go the smartthing app and click on the visonic device. There is a gear icon at the top right corner. Click on it, inside, there is a function type at the end, select smoke detector, then it will change the sensor to smoke detector.

**Comment by Steven-Pierce** [comment]
Yes I’ve got that but I’m monitoring a normally closed contact in my Fire Alarm panel that opens on alarm. With sensor “closed” normal it is reporting as smoke detected. I need to make closed as normal “clear and open as smoke “detected. Thanks for your hep by the way.

________________________________

**Comment by pakmanwg** [comment]
I uploaded a new version 01.03 which support smoke detector closed as clear. Can you try it out to see if you have any problem.
You will need to select the function smoke detector closed as clear

**Comment by Steven-Pierce** [comment]
In the things section it is reporting correctly and changes state correctly but in the Smart Home Monitor it isn’t reporting as a smoke. Still says smoke ok when in alarm.

Sent from my iPhone

On Feb 17, 2018, at 15:51, pakmanwg <notifications@github.com<mailto:notifications@github.com>> wrote:


I uploaded a new version 01.03 which support smoke detector closed as clear. Can you try it out to see if you have any problem.

**Comment by pakmanwg** [comment]
Please try the new version 01.04.  This should fix the issue.

**Comment by Steven-Pierce** [comment]
Everything is working correctly!  Thank you so much for your help and assistance.

Sent from my iPhone

On Feb 17, 2018, at 19:57, pakmanwg <notifications@github.com<mailto:notifications@github.com>> wrote:


Please try the new version 01.04. This should fix the issue.

**Comment by pakmanwg** [comment]
Great to hear that. Enjoy.
